#!/usr/bin/env bash
# Uploads the generated long-context json_kv data (see generate_json_kv_data.py)
# to the allenai/helmet-plus dataset repo on the Hub.
#
# Re-running overwrites whatever's already there: num_kvs is deterministic given
# the same tokenizer/lengths/seed, so filenames (and therefore repo paths) stay
# stable across regenerations, and each upload is just a new commit replacing
# the file content at those paths.
#
# Usage: bash hf_upload.sh   (no arguments)
# Requires: uv (https://docs.astral.sh/uv/), and either a HF_TOKEN (or
# HUGGING_FACE_HUB_TOKEN) in a .env file at the repo root, or having already
# run `uv run hf auth login`. huggingface_hub (which ships the `hf` CLI) is a
# project dependency, so `uv run hf ...` resolves to the project's synced
# environment.
set -euo pipefail

REPO_ID="allenai/helmet-plus"
REPO_TYPE="dataset"
DATA_DIR="data"
MANIFEST="configs/json_kv_long_manifest.json"
MANIFEST_DEST="json_kv/manifest.json"

# Directories under data/ to publish. json_kv is generated by
# generate_json_kv_data.py; the rest is derived data extracted from HELMET's
# data.tar.gz (retrieval output for RAG/re-ranking/Cite, and the keypoint files
# the summarization judge needs). It is re-hosted unpacked so a consumer can
# fetch one file per task and length rather than a 10GB tarball.
#
# Each directory carries a manifest.json mapping length tier -> file, written by
# scripts/build_data_manifests.py, so consumers never hardcode filenames.
DATA_INCLUDES=(
  "json_kv/**"
  "kilt/**"
  "msmarco/**"
  "alce/**"
  "infbench/**"
  "multi_lexsum/**"
)

# ALCE's few-shot prompt files live in the repo rather than the data release;
# uploading them keeps the hosted dataset self-contained.
PROMPT_DIR="prompts"
PROMPT_DEST="alce_prompts"

cd "$(dirname "${BASH_SOURCE[0]}")/.."

if ! command -v uv &> /dev/null; then
  echo "error: uv is not installed. See https://docs.astral.sh/uv/getting-started/installation/" >&2
  exit 1
fi

if [ -f .env ]; then
  echo "Loading .env..."
  set -a
  source .env
  set +a
fi

if ! uv run hf auth whoami &> /dev/null; then
  echo "error: not logged in to the Hub, and no working HF_TOKEN found." >&2
  echo "       Either put HF_TOKEN=hf_... in a .env file at the repo root, or run 'uv run hf auth login'." >&2
  exit 1
fi

# Upload whichever of the directories are present, so this works both for a
# json_kv-only refresh and for a full publish.
present=()
for pattern in "${DATA_INCLUDES[@]}"; do
  if [ -d "$DATA_DIR/${pattern%%/*}" ]; then present+=("$pattern"); fi
done

if [ ${#present[@]} -eq 0 ]; then
  echo "error: none of the expected directories exist under $DATA_DIR/." >&2
  echo "       Run scripts/generate_json_kv_data.py, and/or extract HELMET's" >&2
  echo "       data.tar.gz (see DATA_HOSTING_BRIEF.md) before uploading." >&2
  exit 1
fi

echo "Uploading to $REPO_ID ($REPO_TYPE):"
include_args=()
for pattern in "${present[@]}"; do
  echo "  - $DATA_DIR/${pattern%%/*}/  ($(du -sh "$DATA_DIR/${pattern%%/*}" | cut -f1))"
  # the flag takes a single pattern, so it is repeated rather than passed a list
  include_args+=(--include "$pattern")
done

# `hf upload` supersedes the deprecated `upload-large-folder`; it is still
# chunked and resumable, which matters since this is tens of GB.
uv run hf upload "$REPO_ID" "$DATA_DIR" \
  --repo-type "$REPO_TYPE" \
  "${include_args[@]}" \
  --private

if [ -d "$PROMPT_DIR" ]; then
  echo "Uploading $PROMPT_DIR/ -> $REPO_ID/$PROMPT_DEST/ ..."
  uv run hf upload "$REPO_ID" "$PROMPT_DIR" "$PROMPT_DEST" \
    --repo-type "$REPO_TYPE" \
    --commit-message "Upload ALCE prompt files"
fi

if [ -f "$MANIFEST" ]; then
  echo "Uploading $MANIFEST -> $REPO_ID/$MANIFEST_DEST..."
  uv run hf upload "$REPO_ID" "$MANIFEST" "$MANIFEST_DEST" \
    --repo-type "$REPO_TYPE" \
    --commit-message "Update json_kv manifest"
else
  echo "warning: $MANIFEST not found, skipping manifest upload" >&2
fi

echo "Done: https://huggingface.co/datasets/$REPO_ID"
